### ISSUE TITLE
Running ml info on non-existing env breaks

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#224]
Running `ml info prod` when you don't have prod.properties returns:

```
ERROR: no implicit conversion of nil into String
ERROR: ["deploy/lib/server_config.rb:101:in `+'", "deploy/lib/server_config.rb:101:in `block in info'", "deploy/lib/server_config.rb:100:in `each'", "deploy/lib/server_config.rb:100:in `info'", "deploy/lib/ml.rb:128:in `<main>'"]
```

**Comment by dmcassel** [comment]
fixed in dev
