### ISSUE TITLE
Symbolic link support

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#244]
I frequently use symbolic link to avoid file / directory duplication.
Apparently `ml deploy` command does not support it. Here is the error returned:

```
C:\Users\rlouapre\Projects\ml\marklogic_alm>ml local deploy modules
ERROR: No such file or directory - C:/Users/rlouapre/Projects/ml/marklogic_alm/src/main/node_modules/xquerrail2.framework/node_modules/gulp-header/node_modules/lodash.assign/node_modules/lodash._basecreatecallback/node_modules/lodash.bind/node_modules/lodash._createwrapper/node_modules/lodash.isfunction
ERROR: ["C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:241:in `initialize'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:241:in `open'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:241:in `prep_body'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:122:in `block in load_files'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:115:in `each'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:115:in `each_with_index'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/xcc.rb:115:in `load_files'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:516:in `load_data'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:980:in `block in deploy_src'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:974:in `each'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:974:in `deploy_src'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:960:in `deploy_modules'", "C:/Users/rlouapre/Projects/ml/marklogic_alm/deploy/lib/server_config.rb:478:in `deploy'", "deploy/lib/ml.rb:135:in `<main>'"]
```

Would it be possible to add this feature?

**Comment by grtjn** [comment]
End conclusion: symlinks were not the issues. The part about ignoring files resurfaced in ticket #419, but by then was already covered by the `ignore-folders` property. Closing this ticket.
