### ISSUE TITLE
deploy modules --incremental=yes breaks

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#777]
Invoking `./ml local deploy modules --incremental=yes` (as documented in help) returns:

```
Filtering to files which are newer locally than on the server
ERROR: comparison of String with nil failed
ERROR: ["/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1709:in `>'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1709:in `block in filter_to_newer_files'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1707:in `select'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1707:in `filter_to_newer_files'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1139:in `load_data'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:2002:in `block in deploy_src'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1951:in `each'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1951:in `deploy_src'", "/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:1084:in `deploy'", "deploy/lib/ml.rb:168:in `<main>'"]
```

**Comment by grtjn** [comment]
Thanks to @sashamitrovich for spotting this..

**Comment by RobertSzkutak** [comment]
Fixed in DEV
